#!/bin/bash
set -e

case $1 in 
     
     remove|purge|abort-install|disappear) 

		AUTO_UPGRADE_TOKEN="/var/run/lliurex-up-auto-upgrade.token"
		AUTO_UPGRADE_CONTROL_DIR="/etc/lliurex-up-auto-upgrade"
		AUTO_UPGRADE_CONTROL_JSON="/etc/lliurex-up-auto-upgrade/lliurex-up-auto-upgrade.json"
     
		if  [ -e "${AUTO_UPGRADE_TOKEN}" ]; then
			rm -f "${AUTO_UPGRADE_TOKEN}" || true
		fi

		if [ -f "${AUTO_UPGRADE_CONTROL_JSON}" ];then
          	rm -f "${AUTO_UPGRADE_CONTROL_JSON}" || true
        	fi

	     if [ -d "${AUTO_UPGRADE_CONTROL_DIR}" ];then
            rm -rf "${AUTO_UPGRADE_CONTROL_DIR}" || true
        	fi
		systemctl stop lliurex-up-auto-upgrade.service || true
		systemctl disable lliurex-up-auto-upgrade.service || true
		
     ;;
esac

#DEBHELPER#

exit 0

